export const ARTICLE_PATH = 'article/'

export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const ARTICLE_CATEGORY = 'ARTICLE_CATEGORY'

export const BATCH_ARTICLE = ARTICLE_PATH + ARTICLE_LIST
export const FETCH_ARTICLE = ARTICLE_PATH + ARTICLE_DETAIL
export const FILTER_CATEGORY = ARTICLE_PATH + ARTICLE_CATEGORY
